version: "3.9"

services:
  dev-db:
    image: postgres:latest
    restart: always
    ports:
      - "8627:5432"
    env_file:
      - .env
    volumes:
      - C:\Users\Luisfbejaranob\Workspace\Docker\postgresql-16:/var/lib/postgresql
